---
INVENTORY_CONFIG:
  master_group_name: oceannik_master
  workers_group_name: oceannik_workers

PROJECT_STATUS_FRESH_FILE:
  current_environment:
  current_host:
  environments:
    blue:
      host:
      services: {}
    green:
      host:
      services: {}
